version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  eureka:
    build:
      context: ../eureka
    ports:
      - 8761:8761

  userservice:
    build:
      context: ../userservice
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=postgresql://postgres:5432/users
      - DATABASE_USERNAME=default
      - DATABASE_PASSWORD=secret
      - EUREKA_SERVER_URL=http://eureka:8761/eureka/
      - SPRING_APP_NAME=userservice



