services:
  postgres:
    image: postgres:10
    volumes:
      - ./data/postgres10:/var/lib/postgresql/data

  s3:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
