version: '3.8'

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret

  eureka:
    build:
      context: ../eureka/.
    ports:
      - 8761:8761

  feedservice:
    env_file:
      - ../feedservice/.env
    build:
      context: ../feedservice/.
      dockerfile: Dockerfile
      args:
        - ARCHIVE_FILE_NAME=feedservice.jar
    ports:
      - 8082:8080
    depends_on:
      - postgres

  userservice:
    build:
      context: ../userservice/.
    ports:
      - 8084:8080
    env_file:
      - ../userservice/.env


